version: 1.2.0.{build}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
environment:
  GITHUB_VERSION:
before_build:
- cmd: nuget restore

- ps: |
    Write-Host $env:APPVEYOR_BUILD_VERSION
    Write-Host $env:GITHUB_VERSION
    $appver = $env:APPVEYOR_BUILD_VERSION
    $split = $appver.Split(".")
    $env:GITHUB_VERSION = $split[0]+"."+$split[1]+"."+$split[2]
    Write-Host $env:GITHUB_VERSION
    Update-AppveyorBuild -Version $env:GITHUB_VERSION

build:
  verbosity: minimal
after_build:
- cmd: >-
    del %APPVEYOR_BUILD_FOLDER%\NNS_T\bin\Release\*.xml

    del %APPVEYOR_BUILD_FOLDER%\NNS_T\bin\Release\*.pdb
artifacts:
- path: NNS_T\bin\Release
  name: NNS_T
deploy: off